import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

export function FinancialDashboardChart({ tripId }: { tripId: number }) {
  const { data: plan } = trpc.tripFinances.plan.useQuery({ tripId }, { enabled: !!tripId });
  const [view, setView] = useState<"overview" | "categories">("overview");
  const [range, setRange] = useState<"all" | "30" | "90" | "custom">("all");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const rangeStart = range === "30" ? new Date(Date.now() - 30 * 86_400_000) : range === "90" ? new Date(Date.now() - 90 * 86_400_000) : range === "custom" && from ? new Date(`${from}T00:00:00`) : null;
  const rangeEnd = range === "custom" && to ? new Date(`${to}T23:59:59`) : null;
  const rangeExpenses = useMemo(() => (plan?.actualExpenses ?? []).filter((expense) => { const paidAt = new Date(expense.paidAt); return expense.approvalStatus === "approved" && (!rangeStart || paidAt >= rangeStart) && (!rangeEnd || paidAt <= rangeEnd); }), [plan, rangeStart?.getTime(), rangeEnd?.getTime()]);
  const rangeActualCents = rangeExpenses.reduce((sum, expense) => sum + expense.amountCents, 0);
  const rangeCategories = useMemo(() => Object.entries(rangeExpenses.reduce<Record<string, number>>((totals, expense) => { totals[expense.category] = (totals[expense.category] ?? 0) + expense.amountCents; return totals; }, {})).map(([category, amountCents]) => ({ category, amountCents })), [rangeExpenses]);
  const data = useMemo(() => view === "overview"
    ? [{ name: "Planned budget", amount: ((plan?.totalCostsCents ?? 0) / 100) }, { name: "Approved actual", amount: (rangeActualCents / 100) }, { name: "Variance", amount: Math.abs((rangeActualCents - (plan?.totalCostsCents ?? 0)) / 100) }]
    : rangeCategories.map((entry) => ({ name: entry.category, amount: entry.amountCents / 100 })), [plan, view, rangeActualCents, rangeCategories]);
  const variance = rangeActualCents - (plan?.totalCostsCents ?? 0);
  const hasChartData = data.some((entry) => entry.amount !== 0);
  return <Card><CardHeader><CardTitle className="flex flex-wrap items-center gap-2 text-base"><BarChart3 className="h-4 w-4 text-primary" /> Financial dashboard <span className="ml-auto flex gap-1"><Button size="sm" variant={view === "overview" ? "default" : "outline"} onClick={() => setView("overview")}>Overview</Button><Button size="sm" variant={view === "categories" ? "default" : "outline"} onClick={() => setView("categories")}>Categories</Button></span></CardTitle></CardHeader><CardContent><div className="mb-3 flex flex-wrap gap-2"><select value={range} onChange={(event) => setRange(event.target.value as typeof range)} className="h-9 rounded-md border border-input bg-background px-2 text-sm"><option value="all">All time</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="custom">Custom range</option></select>{range === "custom" && <><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-sm" /><input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-sm" /></>}</div><div className="mb-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-md bg-muted p-2"><p className="text-muted-foreground">Budget</p><p className="font-semibold">${((plan?.totalCostsCents ?? 0) / 100).toFixed(2)}</p></div><div className="rounded-md bg-muted p-2"><p className="text-muted-foreground">Actual</p><p className="font-semibold">${(rangeActualCents / 100).toFixed(2)}</p></div><div className="rounded-md bg-muted p-2"><p className="text-muted-foreground">Variance</p><p className={variance > 0 ? "font-semibold text-destructive" : "font-semibold text-primary"}>{variance > 0 ? "+" : ""}${(variance / 100).toFixed(2)}</p></div></div>{!hasChartData ? <p className="py-8 text-center text-sm text-muted-foreground">Add planned costs or approved actual expenses to populate this chart.</p> : <div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 8, right: 8, left: -12, bottom: 8 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" tick={{ fontSize: 11 }} interval={0} angle={data.length > 3 ? -24 : 0} textAnchor={data.length > 3 ? "end" : "middle"} height={data.length > 3 ? 58 : 30} /><YAxis tick={{ fontSize: 11 }} tickFormatter={(value) => `$${value}`} /><Tooltip formatter={(value: number) => [`$${Number(value).toFixed(2)}`, "Amount"]} /><Legend /><Bar dataKey="amount" name={view === "overview" ? "Amount" : "Approved spend"} fill="hsl(var(--primary))" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div>}</CardContent></Card>;
}
