import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Supplier = { id: number; name: string; invoiceDueAt: Date | string | null; paymentDueCents: number; paidCents: number; paymentStatus: string };

export function SupplierPaymentCalendar({ suppliers }: { suppliers: Supplier[] }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const days = useMemo(() => Array.from({ length: 42 }, (_, index) => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const offset = (first.getDay() + 6) % 7; return new Date(month.getFullYear(), month.getMonth(), index - offset + 1); }), [month]);
  const dueOn = (date: Date) => suppliers.filter((supplier) => supplier.invoiceDueAt && new Date(supplier.invoiceDueAt).getFullYear() === date.getFullYear() && new Date(supplier.invoiceDueAt).getMonth() === date.getMonth() && new Date(supplier.invoiceDueAt).getDate() === date.getDate());
  const today = new Date();
  return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4 text-primary" />Supplier payment calendar</CardTitle></CardHeader><CardContent><div className="mb-3 flex items-center justify-between"><Button size="icon" variant="ghost" onClick={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() - 1, 1))}><ChevronLeft className="h-4 w-4" /></Button><p className="font-medium">{month.toLocaleDateString("en-AU", { month: "long", year: "numeric" })}</p><Button size="icon" variant="ghost" onClick={() => setMonth((current) => new Date(current.getFullYear(), current.getMonth() + 1, 1))}><ChevronRight className="h-4 w-4" /></Button></div><div className="grid grid-cols-7 gap-1 text-center text-[10px] text-muted-foreground">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{days.map((date) => { const entries = dueOn(date); const inMonth = date.getMonth() === month.getMonth(); const overdue = date < new Date(today.getFullYear(), today.getMonth(), today.getDate()); return <div key={date.toISOString()} className={`min-h-16 rounded-md border p-1 text-xs ${inMonth ? "border-border" : "border-transparent opacity-35"}`}><p className="text-muted-foreground">{date.getDate()}</p>{entries.map((supplier) => <p key={supplier.id} className={`mt-1 truncate rounded px-1 ${overdue && supplier.paymentStatus !== "paid" ? "bg-destructive/15 text-destructive" : supplier.paymentStatus === "paid" ? "bg-primary/15 text-primary" : "bg-amber-500/15 text-amber-600"}`} title={`${supplier.name}: $${Math.max(0, supplier.paymentDueCents - supplier.paidCents).toFixed(2)}`}>{supplier.name}</p>)}</div>; })}</div><p className="mt-3 text-xs text-muted-foreground">Amber = due, red = overdue, green = paid. Dates come from each supplier invoice due date.</p></CardContent></Card>;
}
